name: baybe-multi-task-bo
channels:
  - defaults
  - conda-forge
  - pytorch
  # - fastai
dependencies:
  - python>=3.6,<3.12
  - pip
  - ipython
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pip:
     - -e .  # install git checkout of baybe-multi-task-bo in editable mode
     - baybe[simulation]
     - matminer
     - python-ternary
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     # - icecream
     # - jax
     # - numpyro
     # - funsor
     # - neptune-client
     # - neptune-contrib

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
